package v2rayxhttp

import (
	cryptorand "crypto/rand"
	"math/rand"
	"net/http"
	"net/url"
	"strings"

	"golang.org/x/net/http2/hpack"
)

// randIntn returns a non-negative pseudo-random int in [0,n). It wraps math/rand so
// the transport has a single, easily-auditable randomness entry point. Padding
// length jitter and session ids are not security-sensitive (they only blur on-wire
// size signatures), so math/rand is appropriate; tokenish padding CONTENT uses
// crypto/rand below.
func randIntn(n int) int {
	if n <= 0 {
		return 0
	}
	return rand.Intn(n)
}

// applyXPadding attaches the X-Padding obfuscation to a request.
//
// Non-obfs (default, x_padding_obfs_mode=false): the padding is carried as a
// "x_padding=<pad>" query parameter inside the Referer header — exactly the legacy
// Xray behavior the v1 client shipped and which is live-verified against Xray/3x-ui.
//
// Obfs (x_padding_obfs_mode=true): the padding is placed per x_padding_placement
// (cookie|header|query|queryInHeader) under x_padding_key / x_padding_header, with
// the value generated by x_padding_method (repeat-x|tokenish).
func (c *Client) applyXPadding(request *http.Request) {
	m := &c.meta
	if !m.xPaddingObfsMode {
		// Legacy: x_padding query inside the Referer header. The padding bytes are
		// literal '0' (not 'X') to stay byte-identical to the live-verified v1
		// default — the server validates length only, so the filler byte is free,
		// and keeping '0' avoids changing the on-wire default that was confirmed
		// against Xray/3x-ui. obfs mode below uses the configured repeat-x ('X') /
		// tokenish generator instead.
		n := c.paddingRange.rand()
		if n <= 0 {
			return
		}
		pad := strings.Repeat("0", n)
		referer := &url.URL{Scheme: c.scheme, Host: c.host, Path: request.URL.Path}
		rq := referer.Query()
		rq.Set("x_padding", pad)
		referer.RawQuery = rq.Encode()
		request.Header.Set("Referer", referer.String())
		return
	}
	pad := c.generatePadding()
	if pad == "" {
		return
	}
	switch m.xPaddingPlacement {
	case placementCookie:
		request.AddCookie(&http.Cookie{Name: m.xPaddingKey, Value: pad, Path: "/"})
	case placementHeader:
		request.Header.Set(m.xPaddingHeader, pad)
	case placementQuery:
		setQuery(request.URL, m.xPaddingKey, pad)
	case placementQueryInHeader:
		// Build "<scheme>://<host><path>?<key>=<pad>" and put it in the header.
		// Xray assigns RawQuery directly as key+"="+pad WITHOUT url-encoding the
		// padding; padding is base62 / 'X'/'Z' only, so this is safe to replicate.
		u := &url.URL{Scheme: c.scheme, Host: c.host, Path: request.URL.Path}
		u.RawQuery = m.xPaddingKey + "=" + pad
		request.Header.Set(m.xPaddingHeader, u.String())
	}
}

// generatePadding produces a padding value of a random length in the configured
// x_padding_bytes range, using the configured method. For repeat-x the value is N
// literal 'X' bytes (length == N). For tokenish the value is a base62 token whose
// HPACK-Huffman-encoded length is tuned to ~N, so it survives HTTP/2 header
// compression at the expected size.
func (c *Client) generatePadding() string {
	n := c.paddingRange.rand()
	if n <= 0 {
		return ""
	}
	if c.meta.xPaddingMethod == methodTokenish {
		return generateTokenishPaddingBase62(n)
	}
	return strings.Repeat("X", n)
}

const base62Alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

// generateTokenishPaddingBase62 returns a random base62 string whose HPACK Huffman
// encoded length is within +/-2 of target. It mirrors Xray's
// GenerateTokenishPaddingBase62: start from a crypto-random base62 string sized so
// its compressed length is near target (base62 averages ~0.8 raw bytes per encoded
// byte), then iteratively grow/shrink using filler bytes 'X'/'Z' (both have 8-bit,
// i.e. incompressible, Huffman codes) until the Huffman length lands in range, with
// a hard iteration cap.
func generateTokenishPaddingBase62(target int) string {
	if target <= 0 {
		return ""
	}
	// Initial length: base62 Huffman-compresses to roughly 0.8x, so over-allocate.
	initialLen := (target * 10) / 8
	if initialLen < 1 {
		initialLen = 1
	}
	buf := make([]byte, initialLen)
	randBuf := make([]byte, initialLen)
	if _, err := cryptorand.Read(randBuf); err != nil {
		// crypto/rand should not fail; degrade to math/rand jitter rather than panic.
		for i := range randBuf {
			randBuf[i] = byte(randIntn(256))
		}
	}
	for i := range buf {
		buf[i] = base62Alphabet[int(randBuf[i])%len(base62Alphabet)]
	}

	const maxIter = 150
	for iter := 0; iter < maxIter; iter++ {
		encoded := int(hpack.HuffmanEncodeLength(string(buf)))
		switch {
		case encoded < target-2:
			// too short: append an incompressible filler byte.
			if len(buf)%2 == 0 {
				buf = append(buf, 'X')
			} else {
				buf = append(buf, 'Z')
			}
		case encoded > target+2:
			// too long: drop a byte.
			if len(buf) > 1 {
				buf = buf[:len(buf)-1]
			} else {
				return string(buf)
			}
		default:
			return string(buf)
		}
	}
	return string(buf)
}
