// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && with_ebpf

package bpfgen

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	CgroupMapCgroupBypassIpv4            = "cgroup_bypass_ipv4"
	CgroupMapCgroupBypassIpv6            = "cgroup_bypass_ipv6"
	CgroupMapCgroupBypassPort            = "cgroup_bypass_port"
	CgroupMapCgroupControl               = "cgroup_control"
	CgroupMapCgroupHostIpv4              = "cgroup_host_ipv4"
	CgroupMapCgroupHostIpv6              = "cgroup_host_ipv6"
	CgroupMapCgroupSocketBypass          = "cgroup_socket_bypass"
	CgroupMapCgroupTcpRedirect           = "cgroup_tcp_redirect"
	CgroupMapCgroupUdpFlow               = "cgroup_udp_flow"
	CgroupMapCgroupUdpPeer               = "cgroup_udp_peer"
	CgroupMapCgroupUdpRecovery           = "cgroup_udp_recovery"
	CgroupMapCgroupUdpRedirect           = "cgroup_udp_redirect"
	CgroupMapCgroupUdpToken              = "cgroup_udp_token"
	CgroupMapCgroupUidPolicy             = "cgroup_uid_policy"
	CgroupProgSbEbpfConn4Cookie          = "sb_ebpf_conn4_cookie"
	CgroupProgSbEbpfConn4CookieTcp       = "sb_ebpf_conn4_cookie_tcp"
	CgroupProgSbEbpfConn4CookieUdp       = "sb_ebpf_conn4_cookie_udp"
	CgroupProgSbEbpfConn6Cookie          = "sb_ebpf_conn6_cookie"
	CgroupProgSbEbpfConn6CookieTcp       = "sb_ebpf_conn6_cookie_tcp"
	CgroupProgSbEbpfConn6CookieUdp       = "sb_ebpf_conn6_cookie_udp"
	CgroupProgSbEbpfConn6MappedCookie    = "sb_ebpf_conn6_mapped_cookie"
	CgroupProgSbEbpfConn6MappedCookieTcp = "sb_ebpf_conn6_mapped_cookie_tcp"
	CgroupProgSbEbpfConn6MappedCookieUdp = "sb_ebpf_conn6_mapped_cookie_udp"
	CgroupProgSbEbpfRelCookie            = "sb_ebpf_rel_cookie"
	CgroupProgSbEbpfUdp4Cookie           = "sb_ebpf_udp4_cookie"
	CgroupProgSbEbpfUdp6Cookie           = "sb_ebpf_udp6_cookie"
	CgroupProgSbEbpfUdp6MappedCookie     = "sb_ebpf_udp6_mapped_cookie"
	CgroupProgSbEbpfUrcv4C               = "sb_ebpf_urcv4_c"
	CgroupProgSbEbpfUrcv6C               = "sb_ebpf_urcv6_c"
	CgroupProgSbEbpfUrcv6MappedC         = "sb_ebpf_urcv6_mapped_c"
)

// LoadCgroup returns the embedded CollectionSpec for Cgroup.
func LoadCgroup() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Cgroup: %w", err)
	}

	return spec, err
}

// LoadCgroupObjects loads Cgroup and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CgroupObjects
//	*CgroupPrograms
//	*CgroupMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCgroupObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCgroup()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CgroupSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupSpecs struct {
	CgroupProgramSpecs
	CgroupMapSpecs
	CgroupVariableSpecs
}

// CgroupProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupProgramSpecs struct {
	SbEbpfConn4Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.ProgramSpec `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.ProgramSpec `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.ProgramSpec `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.ProgramSpec `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

// CgroupMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupMapSpecs struct {
	CgroupBypassIpv4   *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6   *ebpf.MapSpec `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort   *ebpf.MapSpec `ebpf:"cgroup_bypass_port"`
	CgroupControl      *ebpf.MapSpec `ebpf:"cgroup_control"`
	CgroupHostIpv4     *ebpf.MapSpec `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6     *ebpf.MapSpec `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass *ebpf.MapSpec `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect  *ebpf.MapSpec `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow      *ebpf.MapSpec `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer      *ebpf.MapSpec `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery  *ebpf.MapSpec `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect  *ebpf.MapSpec `ebpf:"cgroup_udp_redirect"`
	CgroupUdpToken     *ebpf.MapSpec `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy    *ebpf.MapSpec `ebpf:"cgroup_uid_policy"`
}

// CgroupVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CgroupVariableSpecs struct {
}

// CgroupObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupObjects struct {
	CgroupPrograms
	CgroupMaps
	CgroupVariables
}

func (o *CgroupObjects) Close() error {
	return _CgroupClose(
		&o.CgroupPrograms,
		&o.CgroupMaps,
	)
}

// CgroupMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupMaps struct {
	CgroupBypassIpv4   *ebpf.Map `ebpf:"cgroup_bypass_ipv4"`
	CgroupBypassIpv6   *ebpf.Map `ebpf:"cgroup_bypass_ipv6"`
	CgroupBypassPort   *ebpf.Map `ebpf:"cgroup_bypass_port"`
	CgroupControl      *ebpf.Map `ebpf:"cgroup_control"`
	CgroupHostIpv4     *ebpf.Map `ebpf:"cgroup_host_ipv4"`
	CgroupHostIpv6     *ebpf.Map `ebpf:"cgroup_host_ipv6"`
	CgroupSocketBypass *ebpf.Map `ebpf:"cgroup_socket_bypass"`
	CgroupTcpRedirect  *ebpf.Map `ebpf:"cgroup_tcp_redirect"`
	CgroupUdpFlow      *ebpf.Map `ebpf:"cgroup_udp_flow"`
	CgroupUdpPeer      *ebpf.Map `ebpf:"cgroup_udp_peer"`
	CgroupUdpRecovery  *ebpf.Map `ebpf:"cgroup_udp_recovery"`
	CgroupUdpRedirect  *ebpf.Map `ebpf:"cgroup_udp_redirect"`
	CgroupUdpToken     *ebpf.Map `ebpf:"cgroup_udp_token"`
	CgroupUidPolicy    *ebpf.Map `ebpf:"cgroup_uid_policy"`
}

func (m *CgroupMaps) Close() error {
	return _CgroupClose(
		m.CgroupBypassIpv4,
		m.CgroupBypassIpv6,
		m.CgroupBypassPort,
		m.CgroupControl,
		m.CgroupHostIpv4,
		m.CgroupHostIpv6,
		m.CgroupSocketBypass,
		m.CgroupTcpRedirect,
		m.CgroupUdpFlow,
		m.CgroupUdpPeer,
		m.CgroupUdpRecovery,
		m.CgroupUdpRedirect,
		m.CgroupUdpToken,
		m.CgroupUidPolicy,
	)
}

// CgroupVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupVariables struct {
}

// CgroupPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCgroupObjects or ebpf.CollectionSpec.LoadAndAssign.
type CgroupPrograms struct {
	SbEbpfConn4Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie"`
	SbEbpfConn4CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_tcp"`
	SbEbpfConn4CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn4_cookie_udp"`
	SbEbpfConn6Cookie          *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie"`
	SbEbpfConn6CookieTcp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_tcp"`
	SbEbpfConn6CookieUdp       *ebpf.Program `ebpf:"sb_ebpf_conn6_cookie_udp"`
	SbEbpfConn6MappedCookie    *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie"`
	SbEbpfConn6MappedCookieTcp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_tcp"`
	SbEbpfConn6MappedCookieUdp *ebpf.Program `ebpf:"sb_ebpf_conn6_mapped_cookie_udp"`
	SbEbpfRelCookie            *ebpf.Program `ebpf:"sb_ebpf_rel_cookie"`
	SbEbpfUdp4Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp4_cookie"`
	SbEbpfUdp6Cookie           *ebpf.Program `ebpf:"sb_ebpf_udp6_cookie"`
	SbEbpfUdp6MappedCookie     *ebpf.Program `ebpf:"sb_ebpf_udp6_mapped_cookie"`
	SbEbpfUrcv4C               *ebpf.Program `ebpf:"sb_ebpf_urcv4_c"`
	SbEbpfUrcv6C               *ebpf.Program `ebpf:"sb_ebpf_urcv6_c"`
	SbEbpfUrcv6MappedC         *ebpf.Program `ebpf:"sb_ebpf_urcv6_mapped_c"`
}

func (p *CgroupPrograms) Close() error {
	return _CgroupClose(
		p.SbEbpfConn4Cookie,
		p.SbEbpfConn4CookieTcp,
		p.SbEbpfConn4CookieUdp,
		p.SbEbpfConn6Cookie,
		p.SbEbpfConn6CookieTcp,
		p.SbEbpfConn6CookieUdp,
		p.SbEbpfConn6MappedCookie,
		p.SbEbpfConn6MappedCookieTcp,
		p.SbEbpfConn6MappedCookieUdp,
		p.SbEbpfRelCookie,
		p.SbEbpfUdp4Cookie,
		p.SbEbpfUdp6Cookie,
		p.SbEbpfUdp6MappedCookie,
		p.SbEbpfUrcv4C,
		p.SbEbpfUrcv6C,
		p.SbEbpfUrcv6MappedC,
	)
}

func _CgroupClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgroup_bpfeb.o
var _CgroupBytes []byte
